// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrbwbjqgzgcbpysedssg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyYndianFnemdjYnB5c2Vkc3NnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDc3NTMsImV4cCI6MjA2OTcyMzc1M30.QP1ddyLE5kEXYLjhwXHJlDT8nhVqOYF9HXu1MFwy138";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});